### ISSUE TITLE
Modify build and configure setup to allow ssh access to the repos instead of the html default

### ISSUE THREAD

**Issue by cianciosa** [ORNL-Fusion/Stellarator-Tools#13]
### Pull Request from experimental_vmec10 to master_dev

- [Stellarator-Tools:experimental_vmec10:Merged](https://github.com/ORNL-Fusion/Stellarator-Tools/pull/10)

### Pull Request from master_dev to master

- [Stellarator-Tools:master_dev:Merged](https://github.com/ORNL-Fusion/Stellarator-Tools/pull/15)

### Test Results.

- [Tests Pass](https://github.com/ORNL-Fusion/Stellarator-Tools/runs/1664041665?check_suite_focus=true)

### Bugs

Continuous integration fails to checkout the remote repository. It looks like it was caused by the ":" in `https://github.com:ORNL-Fusion/PARVMEC.git/` should be "/" when using html access.

- [Stellarator-Tools:experimental_vmec10: Merged](https://github.com/ORNL-Fusion/Stellarator-Tools/pull/14)

**Comment by jonathanschilling** [comment]
I changed `CMakeLists.txt` to have a variable `URL_BASE`, which includes the `github.com:` for SSH and `github.com/` for https. This commit fixes this issue on my computer: https://github.com/ORNL-Fusion/Stellarator-Tools/commit/7f73a598a0a435890f52ab09e8626f0406d284a7
Should I open a new PR?

**Comment by cianciosa** [comment]
Yes I was about to test a fix but you beat me to it. Go a head and open a new pull request to master_dev.

On Jan 7, 2021, at 12:21 PM, Jonathan Schilling <notifications@github.com<mailto:notifications@github.com>> wrote:



I changed CMakeLists.txt to have a variable URL_BASE, which includes the github.com<http://github.com>: for SSH and github.com/<http://github.com/> for https. This commit fixes this issue on my computer: 7f73a59<https://github.com/ORNL-Fusion/Stellarator-Tools/commit/7f73a598a0a435890f52ab09e8626f0406d284a7>
Should I open a new PR?
